// Code generated by "jade.go"; DO NOT EDIT.

package views

import (
	"io"
)

const (
	connectionsform__0 = `<div id="form-container" class="control"><i id="add-new" class="fas fa-plus-circle" title="New connection"></i><a href="/connections-faq"><i id="connections-faq" class="fas fa-question-circle" title="Connections FAQ"></i></a><div id="name-container" class="field is-horizontal"><div class="field-label is-normal"><label class="label" for="name">Connection Name</label></div><div class="field-body"><div class="field"><input type="text" id="name" value="" placeholder=""/></div></div></div><div id="user-container" class="field is-horizontal"><div class="field-label is-normal"><label class="label" for="user">Username</label></div><div class="field-body"><div class="field"><input type="text" id="user" value="" placeholder=""/></div></div></div><div id="pass-container" class="field is-horizontal"><div class="field-label is-normal"><label class="label" for="pass">Password</label></div><div class="field-body"><input type="password" id="pass" value="" placeholder=""/></div></div><div id="host-container" class="field is-horizontal"><div class="field-label is-normal"><label class="label" for="host">Host</label></div><div class="field-body"><input type="text" id="host" value="" placeholder=""/></div></div><div id="port-container" class="field is-horizontal"><div class="field-label is-normal"><label class="label" for="port">Port</label></div><div class="field-body"><input type="text" id="port" value="" placeholder=""/></div></div><div id="db-container" class="field is-horizontal"><div class="field-label is-normal"><label class="label" for="db">Database</label></div><div class="field-body"><input type="text" id="db" value="" placeholder="optional"/></div></div><div id="default-container" class="field is-horizontal"><div class="field-label is-normal"><label class="label" for="default">Default</label></div><div class="field-body"><input type="checkbox" id="is-default"/></div></div></div>`
)

func Jade_connectionsform(wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(connectionsform__0)

}
