// Code generated by "jade.go"; DO NOT EDIT.

package views

import (
	"io"
)

const (
	help__0 = `<!DOCTYPE html><html><head>`
	help__1 = `<title>Prosql</title><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="stylesheet" href="`
	help__2 = `"/><link rel="stylesheet" href="`
	help__3 = `"/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""/><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&amp;display=swap" rel="stylesheet"/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""/><link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&amp;display=swap" rel="stylesheet"/><link rel="stylesheet" href="`
	help__5 = `"/></head><body><div id="navbar"><div class="logo"><a href="/"><img src="/static/images/icon.png" width="60" height="43.35"/></a></div><div class="email {email-class}"><button class="button contact is-pulled-right"><i class="fas fa-envelope"></i><span>&nbsp;&nbsp;</span><span>tech@prosql.io</span></button></div></div><div class="columns"><div class="column"></div><div class="column is-two-fifths"><section><div class="h1 is-size-3 has-text-justified">Can I run prosql in multiple tabs?</div><p class="has-text-justified">Yes. You can open as many tabs as you want. Each tab can connect to a different server.</p></section><section><div class="h1 is-size-3 has-text-justified">On the tables page, the like search does not seem to work ..</div><p class="has-text-justified">Please use wildcard qualifier % before and/or after the search string.</p></section><section><div class="h1 is-size-3 has-text-justified">I did not use prosql for sometime. Now I cannot see my old queries!</div><p class="has-text-justified">By default only queries that you ran in last 10 days are visible. If you want to view older queries, please search using keywords or tags</p></section></div><div class="column"></div></div><script type="module" src="`
	help__6 = `"></script></body></html>`
)

func Help(root string, rev string, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	var css = "/static/" + root + "/css/pages.css?rev=" + rev
	var js = "/static/" + root + "/dist/js/help.js?rev=" + rev
	buffer.WriteString(help__0)

	var common = "/static/" + root + "//css/common.css?rev=" + rev
	buffer.WriteString(help__1)
	WriteEscString("/static/"+root+"/css/all.min.css", buffer)
	buffer.WriteString(help__2)
	WriteEscString("/static/"+root+"/css/bulma.css", buffer)
	buffer.WriteString(help__3)
	WriteEscString(common, buffer)
	buffer.WriteString(help__2)
	WriteEscString(css, buffer)
	buffer.WriteString(help__5)
	WriteEscString(js, buffer)
	buffer.WriteString(help__6)

}
