shopt -s expand_aliases
alias la='ls -la'
alias ga='git add'
alias gau='git add -u'
alias gp='git push'
alias gl='git log --oneline'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit --amend'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
